from typing import Protocol, Optional
from inventory_system.schemas import Card 


class ICardRepository(Protocol):
    async def get_by_id(self, card_id: int) -> Optional[Card]: ...
        
    async def get_card(self, card_id: int) -> Optional[Card]: ...

    async def update(self, card_id: int, **update_data) -> Optional[Card]: ...
        
    async def create(self, **data) -> Optional[Card]: ...
        
    async def delete(self, card_id: int) -> bool: ...
        
    async def list_cards(self, filter_params: CardFilter) -> PaginatedResponse[Card]: ...
        
    async def get_all_cards(self) -> List[Card]: ...
