from typing import Protocol, List, Optional
from inventory_system.schemas import EquipmentItemCreate, EquipmentItemRead, EquipmentDataCreate, EquipmentDataRead

class IEquipmentRepository(Protocol):
    async def get_by_id(self, item_id: int) -> Optional[EquipmentItemRead]: ...
    
    async def get_card_equipment_items(self, card_id: int) -> List[EquipmentItemRead]: ...

    async def create_item(self, card_id: int, item_type: str, description: str) -> Optional[EquipmentItemRead]: ...
    
    async def update_item(self, item_id: int, **update_data) -> Optional[EquipmentItemRead]: ...
    
    async def delete_item(self, item_id: int) -> bool: ...

    async def add_equipment_record(self, item_id: int, new_record: EquipmentDataCreate) -> Optional[EquipmentDataRead]: ...
    
    async def update_equipment_record(self, record_id: int, **update_data) -> Optional[EquipmentDataRead]: ...
    
    async def delete_equipment_record(self, record_id: int) -> bool: ...