"""add_equipmet_description_column_and_table_for_generic_data

Revision ID: 161105b9cb6f
Revises: e559859a550d
Create Date: 2026-01-08 19:35:34.568121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161105b9cb6f'
down_revision: Union[str, Sequence[str], None] = 'e559859a550d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_data_generic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['equipment_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('equipment_items', sa.Column('description', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_items', 'description')
    op.drop_table('equipment_data_generic')
    # ### end Alembic commands ###
