"""Add_code_to_cut_types

Revision ID: 93f551f4dca3
Revises: 161105b9cb6f
Create Date: 2026-01-19 19:44:02.670190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f551f4dca3'
down_revision: Union[str, Sequence[str], None] = '161105b9cb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_types', sa.Column('code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'cut_types', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cut_types', type_='unique')
    op.drop_column('cut_types', 'code')
    # ### end Alembic commands ###
