"""Initial migration

Revision ID: 9f889243410f
Revises: 
Create Date: 2025-12-20 14:44:29.334033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f889243410f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('groung_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('object_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('pipe_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('property_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('inventory_number_eskd', sa.String(length=50), nullable=False),
    sa.Column('gas_pipeline_section', sa.String(length=300), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('described_name', sa.String(length=300), nullable=False),
    sa.Column('build_date_dn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_length', sa.Float(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('object_name_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('folder', sa.String(length=50), nullable=False),
    sa.Column('cut_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cut_type_id'], ['cut_types.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['object_name_id'], ['object_names.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('described_name'),
    sa.UniqueConstraint('folder'),
    sa.UniqueConstraint('gas_pipeline_section'),
    sa.UniqueConstraint('inventory_number'),
    sa.UniqueConstraint('inventory_number_eskd')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('groung_level_id', sa.Integer(), nullable=True),
    sa.Column('pipe_material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['groung_level_id'], ['groung_levels.id'], ),
    sa.ForeignKeyConstraint(['pipe_material_id'], ['pipe_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('cards')
    op.drop_table('property_types')
    op.drop_table('pipe_materials')
    op.drop_table('object_names')
    op.drop_table('groung_levels')
    op.drop_table('districts')
    op.drop_table('cut_types')
    # ### end Alembic commands ###
