"""add_pressure_types_lookup_table

Revision ID: c871b190ef53
Revises: 9f889243410f
Create Date: 2025-12-31 18:15:50.821706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c871b190ef53'
down_revision: Union[str, Sequence[str], None] = '9f889243410f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressure_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.add_column('cards', sa.Column('pressure_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'pressure_types', ['pressure_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'pressure_type_id')
    op.drop_table('pressure_types')
    # ### end Alembic commands ###
