"""refactor_equipment

Revision ID: e559859a550d
Revises: 476d076405b2
Create Date: 2026-01-07 18:59:45.876216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e559859a550d'
down_revision: Union[str, Sequence[str], None] = '476d076405b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('column_type', sa.Enum('BALANCE', 'FACT', 'CUT', name='columntype'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['equipment_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_data_pipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('groung_level_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groung_level_id'], ['groung_levels.id'], ),
    sa.ForeignKeyConstraint(['id'], ['equipment_data.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['pipe_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_data_valves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['equipment_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('groung_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pipe_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('equipment_card_id_fkey')),
    sa.ForeignKeyConstraint(['groung_level_id'], ['groung_levels.id'], name=op.f('equipment_groung_level_id_fkey')),
    sa.ForeignKeyConstraint(['pipe_material_id'], ['pipe_materials.id'], name=op.f('equipment_pipe_material_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('equipment_pkey'))
    )
    op.drop_table('equipment_data_valves')
    op.drop_table('equipment_data_pipes')
    op.drop_table('equipment_data')
    op.drop_table('equipment_items')
    # ### end Alembic commands ###
